image: "ubuntu:19.10"

before_script:
    - apt-get update -qq && apt-get install -y python3 python3-pip make git pandoc
    - pip3 install -r requirements.txt

test:
    stage: test
    script:
        - python3 -m unittest discover
