image: "ubuntu:19.10"

before_script:
    - apt-get update -qq && apt-get install -y python3 python3-pip make git pandoc
    - pip3 install -r requirements.txt

stages:
    - build
    - test
    - package
    - deploy

build:
    stage: build
    script:
        - python3 setup.py install
        - pandoc-acronyms --help

test:
    stage: test
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    script:
        - coverage run --source acronyms -m unittest discover
        - coverage report

# The package stage checks that a package can be created and is always executed.
package:
    stage: package
    script:
        - export PACKAGE_VERSION=$(git describe  --always --tags --abbrev=7 HEAD)
        - echo "Packaging version $PACKAGE_VERSION."
        - python3 setup.py sdist bdist_wheel

# The deploy stage packages and publishes the packages to pypi. It only runs on tags.
deploy:
    only:
        - tags
#    except:
#        - branches
    script:
        - export PACKAGE_VERSION=$(git describe  --always --tags --abbrev=7 HEAD)
        - echo "Packaging version $PACKAGE_VERSION for deployment."
        - python3 setup.py sdist bdist_wheel
        - echo "Deploying to pypi..."
        - echo "TODO"
