image: "ubuntu:19.10"

before_script:
    - apt-get update -qq && apt-get install -y python3 python3-pip make git pandoc
    - pip3 install -r requirements.txt

build:
    stage: build
    script:
        - python3 setup.py install
        - pandoc-acronyms --help

test:
    stage: test
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    script:
        - coverage run --source acronyms -m unittest discover
        - coverage report

# The deploy stage packages and publishes to pypi on tags and test pypi during development.
# The environment variables for the API tokens must be set in CI accordingly.
deploy-to-test:
    stage: deploy
    except:
        - tags
        - master
    script:
# The .dev suffix marks a "pre-release" version in pip logic:
        - export SUFFIX=".dev"
        - export TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
        - export TWINE_PASSWORD=$TEST_API_TOKEN
        - ./deploy.sh

# Merges to master are published to main pip, but marked as developer releases:
deploy-to-beta:
    stage: deploy
    only:
        - master
    script:
        - export SUFFIX=".dev"
        - export TWINE_PASSWORD=$PROD_API_TOKEN
        - ./deploy.sh

# Tags mark released versions and go to pip as final releases:
deploy-to-prod:
    stage: deploy
    only:
        - tags
    script:
# No .dev here, just the numerical version:
        - export TWINE_PASSWORD=$PROD_API_TOKEN
        - ./deploy.sh
